import React, { Component } from 'react';
import UniversalForm from '../../../utils/UniversalForm';
import CategoryService from '../../../services/CategoryService';

class CreateCategory extends Component {
    constructor(props) {
        super(props);

        this.service = CategoryService.create;
    }

    render() {
        return (
            <React.Fragment>
                <UniversalForm title="Create Category" service={this.service} redirectTo='/categories'>
                <input type="text" name="title" title="Title"  />
                <input type="text" name="slug" title="Slug" autogenerated="true"/>
                </UniversalForm>
            </React.Fragment>
        )
    }
}

export default CreateCategory;